# Generated by Django 3.2 on 2022-09-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='NomParking', max_length=50)),
                ('Nombre_Place', models.IntegerField(default=1)),
                ('Prix_Periode', models.FloatField(default=1)),
                ('Prix_Abonnement', models.FloatField(default=60)),
                ('Date_ouverture', models.TimeField()),
                ('Date_fermeture', models.TimeField()),
                ('Telephone', models.IntegerField()),
                ('Email', models.EmailField(max_length=50)),
                ('Description', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
