# Generated by Django 3.2 on 2022-09-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Nom_Client',
            field=models.CharField(default='NomClient', max_length=50),
        ),
    ]
