# Generated by Django 3.2 on 2022-09-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Description',
        ),
    ]
